Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2980
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
Game 16: Correct word is horse, guess is words
"POST /submit_guess/ HTTP/1.1" 200 281
Game 16: Correct word is horse, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 279
Game 16: Correct word is horse, guess is horse
Internal Server Error: /submit_guess/
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
wordle.models.Leaderboard.DoesNotExist: Leaderboard matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Python311\Lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'score' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 104, in submit_guess
    update_leaderboard(request.user, is_win)
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 124, in update_leaderboard
    leaderboard_entry, created = Leaderboard.objects.get_or_create(user=user)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Python311\Lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'score' cannot be null")
"POST /submit_guess/ HTTP/1.1" 500 221201
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2980
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
Game 17: Correct word is nudge, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 278
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 18: Correct word is uncap, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 281
Game 18: Correct word is uncap, guess is audio
"POST /submit_guess/ HTTP/1.1" 200 280
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 19: Correct word is horse, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 280
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 20: Correct word is nudge, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 280
Game 20: Correct word is nudge, guess is crane
"POST /submit_guess/ HTTP/1.1" 200 280
"GET /game/ HTTP/1.1" 200 3353
"POST /game/ HTTP/1.1" 200 53
Game 21: Correct word is coast, guess is wordl
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3353
"GET /static/users/main.css HTTP/1.1" 200 1373
"GET /static/wordle/css/styles.css HTTP/1.1" 200 3086
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10461
"GET /static/users/favicon.ico HTTP/1.1" 200 1150
"POST /game/ HTTP/1.1" 200 53
Game 22: Correct word is mayor, guess is hurde
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10485
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10485
"GET /static/users/main.css HTTP/1.1" 200 1373
"GET /static/wordle/css/styles.css HTTP/1.1" 200 3086
"GET /static/users/favicon.ico HTTP/1.1" 200 1150
"POST /game/ HTTP/1.1" 200 53
Game 23: Correct word is ghost, guess is hurdl
"POST /submit_guess/ HTTP/1.1" 200 279
Game 23: Correct word is ghost, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3353
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10464
"POST /game/ HTTP/1.1" 200 53
Game 24: Correct word is horse, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 279
"GET /game/ HTTP/1.1" 200 3355
"GET /static/users/main.css HTTP/1.1" 200 1373
"GET /static/wordle/js/scripts.js HTTP/1.1" 200 10464
"GET /static/wordle/css/styles.css HTTP/1.1" 200 3086
"GET /static/users/favicon.ico HTTP/1.1" 200 1150
"POST /game/ HTTP/1.1" 200 53
Game 25: Correct word is fiber, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 278
Game 25: Correct word is fiber, guess is uncap
"POST /submit_guess/ HTTP/1.1" 200 278
Game 25: Correct word is fiber, guess is pious
"POST /submit_guess/ HTTP/1.1" 200 279
Game 25: Correct word is fiber, guess is fiber
Internal Server Error: /submit_guess/
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
wordle.models.Leaderboard.DoesNotExist: Leaderboard matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Python311\Lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'score' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 104, in submit_guess
    update_leaderboard(request.user, is_win)
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 124, in update_leaderboard
    leaderboard_entry, created = Leaderboard.objects.get_or_create(user=user)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\Python311\Lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'score' cannot be null")
"POST /submit_guess/ HTTP/1.1" 500 221203
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/ HTTP/1.1" 200 3355
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
"POST /game/ HTTP/1.1" 200 53
Game 27: Correct word is uncap, guess is happy
"POST /submit_guess/ HTTP/1.1" 200 281
Game 27: Correct word is uncap, guess is uncap
"POST /submit_guess/ HTTP/1.1" 200 284
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/ HTTP/1.1" 200 3355
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
"POST /game/ HTTP/1.1" 200 53
Game 28: Correct word is lapel, guess is happy
Internal Server Error: /submit_guess/
Traceback (most recent call last):
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Roaming\Python\Python311\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py", line 76, in submit_guess
    feedback[i]['result'] = 'correct'
    ~~~~~~~~^^^
IndexError: list index out of range
"POST /submit_guess/ HTTP/1.1" 500 91493
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\james\Bootcamp\projects\project-75-emans-wordle\wordle_gato365\wordle\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/ HTTP/1.1" 200 3355
"GET /static/wordle/js/scripts.js HTTP/1.1" 304 0
